CREATE TABLE IF NOT EXISTS orders (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    invoice_no VARCHAR(30) NOT NULL,
    invoice_token CHAR(36) NOT NULL,
    customer_id BIGINT UNSIGNED NULL DEFAULT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    order_type ENUM('DIRECT_SALE', 'PRE_ORDER') NOT NULL,
    status ENUM('DRAFT', 'DP_PAID', 'PAID', 'READY', 'COMPLETED', 'CANCELLED') NOT NULL,
    pickup_date DATE NULL DEFAULT NULL,
    notes TEXT NULL,
    subtotal DECIMAL(14,2) NOT NULL,
    discount_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    total_amount DECIMAL(14,2) NOT NULL,
    total_hpp DECIMAL(14,2) NOT NULL,
    total_paid DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    payment_method ENUM('CASH', 'TRANSFER', 'QRIS') NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    UNIQUE KEY uk_orders_invoice_no (invoice_no),
    UNIQUE KEY uk_orders_invoice_token (invoice_token),
    INDEX idx_orders_status_order_type (status, order_type),
    INDEX idx_orders_created_at (created_at),
    INDEX idx_orders_pickup_date (pickup_date),
    INDEX idx_orders_deleted_at (deleted_at),
    CONSTRAINT fk_orders_customer_id FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
    CONSTRAINT fk_orders_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
